# Generated by Django 3.0 on 2022-09-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customerOrderStatus',
            field=models.ForeignKey(default='ea5f7840-ccaf-45c6-a518-fbcedb1fc57d', on_delete=django.db.models.deletion.CASCADE, to='back_end_application.CustomerOrderStatus'),
            preserve_default=False,
        ),
    ]
