# Generated by Django 3.0 on 2022-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0004_remove_product_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='orderContents',
            field=models.CharField(default=[], max_length=500),
            preserve_default=False,
        ),
    ]
