# Generated by Django 4.1.2 on 2022-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0005_customerorder_ordercontents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='orderContents',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='orderContents',
            field=models.ManyToManyField(to='back_end_application.product'),
        ),
    ]
