# Generated by Django 4.1.2 on 2022-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0007_remove_customerorder_ordercontents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='products',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='products',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
