# Generated by Django 4.1.2 on 2022-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_application', '0008_remove_customerorder_products_customerorder_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customerOrderStatus',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='orderStatus',
            field=models.CharField(default='Completed', max_length=150),
            preserve_default=False,
        ),
    ]
